name:                snailrace
version:             0.1.0.0
github:              "PaulBrownMagic/snailrace"
license:             BSD3
author:              "Paul Brown"
maintainer:          "pbrownpaul@gmail.com"
copyright:           "2018 Paul Brown"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/PaulBrownMagic/snailrace#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  snailrace-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snailrace

tests:
  snailrace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snailrace
